---
name: test-actions-windows-bash
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  normal:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: ./
        with:
          aqua_version: v1.26.2
      - run: command -v aqua
        shell: bash
      - run: aqua -v
        shell: bash
      - run: actionlint -version
        shell: bash
        working-directory: tests

      - run: command -v aqua
      - run: aqua -v
      - run: actionlint -version
        working-directory: tests
  working_dir:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: ./
        with:
          aqua_version: v1.26.2
          working_directory: tests

      - run: command -v aqua
        shell: bash
      - run: aqua -v
        shell: bash
      - run: github-comment -v
        shell: bash
        working-directory: tests

      - run: command -v aqua
      - run: aqua -v
      - run: github-comment -v
        working-directory: tests
