---
name: test-actions
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: ./
        with:
          aqua_version: v1.21.0
          working_directory: tests
      - run: command -v aqua
      - run: aqua -v
      - run: github-comment -v
        working-directory: tests
  set-absolute-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: ./
        with:
          aqua_version: v1.21.0
          install_path: /tmp/bin/aqua
          working_directory: tests
      - run: /tmp/bin/aqua -v
  set-relative-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: ./
        with:
          aqua_version: v1.21.0
          install_path: bin/aqua
          working_directory: tests
      - run: tests/bin/aqua -v
